[project]
name = "cars"
version = "0.1.0"
description = "A site for managing cars collections"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cloudinary>=1.44.1",
    "firebase-admin>=7.1.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
